version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: task_planner
      POSTGRES_PASSWORD: task_planner
      POSTGRES_DB: task_planner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      internal_network:
        ipv4_address: локальный адрес


  task_planner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      internal_network:
        ipv4_address: локальный адрес

volumes:
  postgres_data:


networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: локальный адрес