name: CI Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Укажите нужную версию Python

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi --no-root

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U test; do sleep 1; done

      - name: Run tests
        env:
          CONFIG_FILE: /usr/task_planner/task_planner/test/test_config.yaml
          STATIC_DIR: /usr/task_planner/task_planner/static
          TEMPLATES_DIR: /usr/task_planner/task_planner/templates
        run: |
          poetry run pytest /usr/task_planner/test

      - name: Clean up containers
        if: always()
        run: |
          docker rm -f task_planner || true